# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: source/requirements.txt

formats: all
